# Generated by Django 4.2.24 on 2025-09-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienvenida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.BigIntegerField(default=0),
        ),
    ]
